# Generated by Django 5.2.5 on 2025-08-08 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('price', models.FloatField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='')),
                ('category', models.CharField(default='body', max_length=10)),
                ('description', models.TextField(default='Get a whole new experience with the best product you could have.')),
                ('for_type', models.CharField(default='Normal', max_length=10)),
            ],
        ),
    ]
