# Generated by Django 5.2.5 on 2025-08-09 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_remove_product_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('body', 'Body'), ('face', 'Face'), ('lips', 'Lips')], default='body', max_length=20),
        ),
    ]
