# Generated by Django 5.2.5 on 2025-08-09 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_product_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='for_type',
            field=models.CharField(choices=[('oily', 'Oily'), ('dry', 'Dry'), ('mixed', 'Mixed'), ('sensitive', 'Sensitive'), ('normal', 'Normal')], default='Normal', max_length=10),
        ),
    ]
