# Generated by Django 5.2.5 on 2025-08-10 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_alter_product_for_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='warranty',
            field=models.CharField(choices=[('none', 'None'), ('seller', 'Seller'), ('brand', 'Brand')], default='none', max_length=20),
        ),
        migrations.AlterField(
            model_name='product',
            name='for_type',
            field=models.CharField(choices=[('oily', 'Oily'), ('dry', 'Dry'), ('mixed', 'Mixed'), ('sensitive', 'Sensitive'), ('normal', 'Normal')], default='normal', max_length=10),
        ),
    ]
