# Generated by Django 5.2.8 on 2025-11-22 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_shippingaddress'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='warranty',
            field=models.CharField(choices=[('nivea', 'Nivea'), ('loreal', 'Loreal'), ('dove', 'Dove'), ('olay', 'Olay'), ('clinique', 'Clinique'), ('himalaya', 'Himalaya'), ('bareanatomy', 'Bareanatomy'), ('cetaphil', 'Cetaphil'), ('aveeno', 'Aveeno'), ('cerave', 'Cerave')], default='none', max_length=20),
        ),
    ]
