# Generated by Django 5.2.8 on 2026-01-06 14:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0010_confirmedorder'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='confirmedorder',
            name='order',
        ),
        migrations.AddField(
            model_name='confirmedorder',
            name='order_number',
            field=models.CharField(max_length=100, null=True, unique=True),
        ),
        migrations.CreateModel(
            name='ConfirmedOrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=200)),
                ('price_at_purchase', models.FloatField()),
                ('quantity', models.IntegerField()),
                ('confirmed_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='store.confirmedorder')),
            ],
        ),
    ]
